### ISSUE TITLE
pre-train时epoch设置问题

### ISSUE THREAD

**Issue by shaoyn0817** [unreliableXu/TensorFlow_RLRE#10]
你好 请问一下 在pretrain阶段（pretrain cnn和rl的时候） 是需要把两个网络train到完全收敛吗？

**Comment by unreliableXu** [comment]
cnn阶段训练了三轮。在原论文中rl以及cnn+rl阶段，epoch都有固定的值，比如20。

**Comment by unreliableXu** [comment]
可以直接返回reward，但是原始代码中也是这样实现的，这应该是对应强化学习中使用advantage function进行策略梯度下降的方案。
