### ISSUE TITLE
Issue with the test code (poor performance)

### ISSUE THREAD

**Issue by shubhamjha97** [unreliableXu/TensorFlow_RLRE#13]
Running the test code on the provided dataset using the best models gives very poor performance.
Here are the p@n scores I got-
```
best_cnn_P@100,200,300: [0.04, 0.03, 0.02]
```
I get quite similar scores even if I train the CNN model and then run tests.
Could it possibly be an issue with the test code?
I'm currently using Tensorflow version 1.6.0 on Python 3.5.

**Comment by unreliableXu** [comment]
After downloading the project and running initial.py, test.py, I get the same result as I mentioned in Readme.
best_cnn_P@100,200,300: [0.8, 0.735, 0.7066666666666667]

**Comment by shubhamjha97** [comment]
So, after updating to Python 3.6.5, here are my test results-
```
best_cnn_P@100,200,300: [0.8, 0.735, 0.7066666666666667]
origin_cnn_P@100,200,300: [0.43, 0.39, 0.37]
```
I used the hyperparameters that are present in the code.

Can you share the hyperparameters that you used while training the best models?
