### ISSUE TITLE
Question about parameters updating

### ISSUE THREAD

**Issue by hustlrr** [unreliableXu/TensorFlow_RLRE#14]
Hi, 
Thanks for your code. I have a question about parameters updating. 
In Algorithm 2 of the paper, after computing delayed reward for **one** bag, the original policy network will be updated (See: `Update the parameter Theta of instance selector...`). 
But in `rlmodel.py`, my understanding is that both the original policy network and the target policy network are updated after the decision process of **all** bags (line 308 for the original one, and line 317 for the target one), and the gradient is the sum of **all** bags (`+=` of line 279). 
So, do I understand your code wrongly? Or the implementation is different from Algorithm 2? 
Thanks.

**Comment by unreliableXu** [comment]
I think you understanding of my codes is right. But in the original c++ implementation, it is updating the parameters of  the original policy network after all bags. In RL.cpp, the variable featureW will be used to get the action and will be updated after all bags.

**Comment by hustlrr** [comment]
Thanks for your prompt reply. I will see the C++ implementation for more details.
