### ISSUE TITLE
About the sentence size

### ISSUE THREAD

**Issue by whu20122015** [unreliableXu/TensorFlow_RLRE#17]
chosen sentence size: 364691
total_reward: -0.150552
best_reward -0.150552
Excuse me， the total sentence size is 280579, why the chosen size is 364691 which is lager than total sentence size?

**Comment by unreliableXu** [comment]
As described in origin paper, there are 522,611 sentences, 281,270 entity pairs, and 18,252 relational facts in the training data; and 172,448 sentences, 96,678 entity pairs and 1,950 relational facts in the test data.

**Comment by whu20122015** [comment]
Thanks， by the way, how can I get the 364,691 sentences chosen by the model?

**Comment by unreliableXu** [comment]
You could use the RL model to do the selection.
