### ISSUE TITLE
重新训练完之后找不到best_model啊。

### ISSUE THREAD

**Issue by imnujf** [unreliableXu/TensorFlow_RLRE#22]
![image](https://user-images.githubusercontent.com/26041804/48884921-54fe7200-ee61-11e8-88cc-cbb532b04b6e.png)

**Comment by imnujf** [comment]
![image](https://user-images.githubusercontent.com/26041804/48884863-254f6a00-ee61-11e8-8bf8-3feb08e999b2.png)

**Comment by imnujf** [comment]
![image](https://user-images.githubusercontent.com/26041804/48884888-3e581b00-ee61-11e8-8e13-4618bfac1007.png)

**Comment by unreliableXu** [comment]
你可以使用seleced和union的模型进行分类。现在提供的best_model是我重命名的实验中效果最好的模型。代码并不会产生。

**Comment by jiadd** [comment]
> 你可以使用seleced和union的模型进行分类。现在提供的best_model是我重命名的实验中效果最好的模型。代码并不会产生。

您好，理论上seleced模型是不是应该比origin效果好才对啊？
