### ISSUE TITLE
如果一个句子有多个实体对关系的问题

### ISSUE THREAD

**Issue by whu20122015** [unreliableXu/TensorFlow_RLRE#25]
请问一下，目前的实验都是一个句子只有一个实体对与关系，，，如果一个句子有多个实体对之间的关系，是不是就不能处理了？也无法分bag训练了？

**Comment by unreliableXu** [comment]
我觉得同一个句子中每一个实体对以及其对应的关系都可以构成一个训练样本，分开处理。现在的模型确实是没有办法同时预测一个句子中多个实体对的关系类别的。
