### ISSUE TITLE
initial.py with error

### ISSUE THREAD

**Issue by loveJasmine** [unreliableXu/TensorFlow_RLRE#26]
ub16c9@ub16c9-gpu:~/ub16_prj/TensorFlow_RLRE$ python3.6 initial.py
reading train data...
Traceback (most recent call last):
  File "initial.py", line 482, in <module>
    init_entityebd()
  File "initial.py", line 393, in init_entityebd
    en1 = content[2]
IndexError: list index out of range
ub16c9@ub16c9-gpu:~/ub16_prj/TensorFlow_RLRE$

**Comment by WJYw** [comment]
Hello, I have encountered the same problem as you. Are you solving it? Is it convenient to provide a solution?

**Comment by zwd13122889** [comment]
@loveJasmine @WJYw 您好，问一下，我origin_data目录下的train.txt文件中只有一个网址，请问下，训练数据怎么获得
