### ISSUE TITLE
selected_cnn_model.ckpt保存后似乎没有使用

### ISSUE THREAD

**Issue by shaoyn0817** [unreliableXu/TensorFlow_RLRE#5]
Hi 在rlmodel.py的最后一行（448行）保存了一个selected_cnn_model.ckpt，但是在后面的代码中似乎没有用到这个ckpt，在cnnrlmodel.py里的171行interact = cnnmodel.interaction(sess1,save_path='model/origin_cnn_model.ckpt')，这里的origin_cnn_model.ckpt是否应该换成selected_cnn_model.ckpt呢？

**Comment by unreliableXu** [comment]
selected_cnn_model.ckpt 是利用强化学习模型选择出来的数据训练的cnn模型，可以直接用于测试。
在联合训练阶段，论文中是使用在原始数据集上已经训练好的cnn模型，接着在强化学习模型选择的数据集上更新参数，所以在cnnrlmodel.py中使用的还是origin_cnn_model.ckpt。
